##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
url: ellabelle.github.io
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
baseurl: /19thCenturyHealthcareinNiagaraRegion
# location of code, the full url to your github repository
source-code: https://ellabelle.github.io/19thCenturyHealthcareinNiagaraRegion

##########
# SITE SETTINGS
#
# title of site appears in banner
title: 19th Century Healthcare in Niagara Region
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: A look into Healthcare in the Niagara Region in the long 19th century. 
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: Our exhibition is a series of images that shows what healthcare looked like in the long 19th century around the Niagara Region, a special thanks to the Brock Archives & Special Collections, as well as the Niagara Falls Public Library for the use of the images.
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Ella Bos and Morgan Sarah Jane Branton

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: metadataspreadsheetfinal

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
